executor: KubernetesExecutor
flower:
  enabled: false
redis:
  enabled: false
Users:
  username: NickLimber
  password: NickLimber
  role: Admin
  email: nlimber@proton.me
  firstName: Nick
  lastName: Limber
postgresql:
  enabled: true
persistence:
  enabled: true
  storageClass: ""
  size: 8Gi